namespace CoverageManager.Connector;

/// <summary>
/// Settings for the Live Bridge consumer feed (TheBridge product spec, section 15, proposal 14), bound from the
/// <c>LiveBridge</c> config section. Only consulted when <c>MT5:Provider</c> is <see cref="MT5ApiProviders.LiveBridge"/>.
/// </summary>
public sealed class LiveBridgeOptions
{
    public const string SectionName = "LiveBridge";

    /// <summary>
    /// "Connect to feed" switch. <b>Default false, in code</b>: while false, <see cref="LiveBridgeApi.Connect"/> refuses
    /// before looking at the URL or key, so nothing dials the feed -- not a <c>dotnet run</c>, not a double-clicked exe,
    /// not a process that happens to inherit a feed key from its environment. Only a service configuration that sets
    /// <c>LiveBridge__Enabled=true</c> alongside its own key can connect. Reason: the bridge replaces a same-name
    /// consumer on connect, so an accidental launch holding v1's key would displace live v1 (seen 2026-09-13: a copy of
    /// v1's key sat in a user environment that any launch on the server would have inherited).
    /// </summary>
    public bool Enabled { get; set; } = false;

    /// <summary>Feed endpoint; the URL path names the source, e.g. <c>wss://feed.connecttrader.app:5571/feed/BBcorp-Live</c>.</summary>
    public string Url { get; set; } = "";

    /// <summary>
    /// Bearer key generated by the bridge console. Environment only (<c>LiveBridge__ApiKey</c>), never appsettings.json -
    /// that file is tracked in git. Empty = Connect fails at once with a clear message, without dialing.
    /// </summary>
    public string ApiKey { get; set; } = "";

    /// <summary>
    /// Path to a file holding ONLY the bearer key (surrounding whitespace / a trailing newline ignored), kept outside the
    /// repo in an ACL-locked folder -- the same pattern as <c>Postgres:PasswordFile</c>. v2 default:
    /// <c>C:\ProgramData\CoverageManagerV2\secrets\livebridge_v2_key.txt</c>. Read on every <see cref="LiveBridgeApi.Connect"/>,
    /// so a rotated key is picked up by the next fresh session. Setting BOTH this and <see cref="ApiKey"/> is refused:
    /// a key inherited from some environment must never silently replace the one in the file (see <see cref="Enabled"/>).
    /// </summary>
    public string ApiKeyFile { get; set; } = "";

    /// <summary>
    /// The key to dial with, from <see cref="ApiKey"/> or <see cref="ApiKeyFile"/> (exactly one). On failure
    /// <paramref name="error"/> says why; it names the setting and the path, never the key or any file content.
    /// </summary>
    public bool TryResolveApiKey(out string key, out string error)
    {
        key = "";
        var hasEnv = !string.IsNullOrWhiteSpace(ApiKey);
        var hasFile = !string.IsNullOrWhiteSpace(ApiKeyFile);

        if (hasEnv && hasFile)
        {
            error = "both LiveBridge__ApiKey and LiveBridge:ApiKeyFile are set; set exactly one (v2: the key file, and remove LiveBridge__ApiKey from the environment)";
            return false;
        }
        if (hasEnv)
        {
            key = ApiKey.Trim();
            error = "";
            return true;
        }
        if (!hasFile)
        {
            error = "no feed key: set LiveBridge:ApiKeyFile to a file holding the key the bridge console generated (or the environment variable LiveBridge__ApiKey)";
            return false;
        }

        string text;
        try
        {
            if (!File.Exists(ApiKeyFile)) { error = $"LiveBridge:ApiKeyFile '{ApiKeyFile}' does not exist or this account cannot see it"; return false; }
            text = File.ReadAllText(ApiKeyFile);
        }
        catch (Exception ex)
        {
            error = $"LiveBridge:ApiKeyFile '{ApiKeyFile}' could not be read ({ex.GetType().Name}); check the file ACL grants this service account read access";
            return false;
        }

        var trimmed = text.Trim();
        if (trimmed.Length == 0) { error = $"LiveBridge:ApiKeyFile '{ApiKeyFile}' is empty"; return false; }
        if (trimmed.Any(c => char.IsWhiteSpace(c) || char.IsControl(c)))
        {
            error = $"LiveBridge:ApiKeyFile '{ApiKeyFile}' must hold only the key on one line (found whitespace or control characters inside it)";
            return false;
        }
        key = trimmed;
        error = "";
        return true;
    }

    /// <summary>
    /// Where the last applied sequence per stream is kept between runs (a small JSON file), so a restart resumes instead
    /// of taking a snapshot. Empty = <c>%LOCALAPPDATA%\CoverageManager\livebridge-state.json</c>, which survives a
    /// <c>publish\api</c> swap.
    /// </summary>
    public string StatePath { get; set; } = "";

    /// <summary>First wait before a reconnect; doubles per failed attempt up to <see cref="ReconnectMaxMs"/>.</summary>
    public int ReconnectMs { get; set; } = 1000;

    public int ReconnectMaxMs { get; set; } = 30000;

    /// <summary>
    /// After this many reconnect attempts in a row fail, the adapter reports itself disconnected so the connection
    /// service starts a fresh session (which takes a new snapshot). 0 = never give up. With the backoff above the
    /// default of 20 attempts is about nine minutes.
    /// </summary>
    public int ReconnectGiveUpAttempts { get; set; } = 20;

    /// <summary>
    /// No frame for this long = dead line: the socket is dropped and a resume reconnect follows. The contract says 15 s
    /// (the bridge heartbeats every 5 s when nothing else is sent).
    /// </summary>
    public int SilenceLimitMs { get; set; } = 15000;

    /// <summary>hello through snapshot_end / replay_end must complete within this.</summary>
    public int HandshakeTimeoutMs { get; set; } = 30000;

    /// <summary>Ack cadence (the bridge's Health page shows it as the consumer's lag); 0 disables acks.</summary>
    public int AckEveryMs { get; set; } = 5000;

    /// <summary>How long received deals stay answerable through <see cref="IMT5Api.RequestDeals"/>.</summary>
    public int DealRetentionHours { get; set; } = 48;

    /// <summary>Debounce for writing the sequence file after a record is applied; 0 = write-through.</summary>
    public int SequenceFlushMs { get; set; } = 500;

    /// <summary>
    /// Safety margin added to the instant from which the feed's deal stream is known to be complete (this process's
    /// resume point, or the end of a deals replay gap) before the adapter reports it as the start of its deal history
    /// (<see cref="IMT5DealHistory"/>). It absorbs clock skew between the MT5 server that stamps deal times and the
    /// bridge that admits them, so a deal stamped just after the boundary but admitted just before it is never taken
    /// for a ghost by the reconciliation sweep. 5 minutes by default.
    /// </summary>
    public int DealHistoryMarginMs { get; set; } = 300_000;

    /// <summary>
    /// Optional pin: accept only the server certificate with this SHA-1 thumbprint (a self-signed feed certificate).
    /// Empty = the operating system's trust store decides, as for any HTTPS client.
    /// </summary>
    public string CertificateThumbprint { get; set; } = "";

    public string ResolveStatePath()
    {
        if (!string.IsNullOrWhiteSpace(StatePath)) return StatePath;
        var local = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
        var root = string.IsNullOrEmpty(local) ? AppContext.BaseDirectory : Path.Combine(local, "CoverageManager");
        return Path.Combine(root, "livebridge-state.json");
    }
}
