namespace CoverageManager.Connector;

/// <summary>
/// Settings for the Live Bridge consumer feed (TheBridge product spec, section 15, proposal 14), bound from the
/// <c>LiveBridge</c> config section. Only consulted when <c>MT5:Provider</c> is <see cref="MT5ApiProviders.LiveBridge"/>.
/// </summary>
public sealed class LiveBridgeOptions
{
    public const string SectionName = "LiveBridge";

    /// <summary>Feed endpoint; the URL path names the source, e.g. <c>wss://feed.connecttrader.app:5571/feed/BBcorp-Live</c>.</summary>
    public string Url { get; set; } = "";

    /// <summary>
    /// Bearer key generated by the bridge console. Environment only (<c>LiveBridge__ApiKey</c>), never appsettings.json -
    /// that file is tracked in git. Empty = Connect fails at once with a clear message, without dialing.
    /// </summary>
    public string ApiKey { get; set; } = "";

    /// <summary>
    /// Where the last applied sequence per stream is kept between runs (a small JSON file), so a restart resumes instead
    /// of taking a snapshot. Empty = <c>%LOCALAPPDATA%\CoverageManager\livebridge-state.json</c>, which survives a
    /// <c>publish\api</c> swap.
    /// </summary>
    public string StatePath { get; set; } = "";

    /// <summary>First wait before a reconnect; doubles per failed attempt up to <see cref="ReconnectMaxMs"/>.</summary>
    public int ReconnectMs { get; set; } = 1000;

    public int ReconnectMaxMs { get; set; } = 30000;

    /// <summary>
    /// No frame for this long = dead line: the socket is dropped and a resume reconnect follows. The contract says 15 s
    /// (the bridge heartbeats every 5 s when nothing else is sent).
    /// </summary>
    public int SilenceLimitMs { get; set; } = 15000;

    /// <summary>hello through snapshot_end / replay_end must complete within this.</summary>
    public int HandshakeTimeoutMs { get; set; } = 30000;

    /// <summary>Ack cadence (the bridge's Health page shows it as the consumer's lag); 0 disables acks.</summary>
    public int AckEveryMs { get; set; } = 5000;

    /// <summary>How long received deals stay answerable through <see cref="IMT5Api.RequestDeals"/>.</summary>
    public int DealRetentionHours { get; set; } = 48;

    /// <summary>Debounce for writing the sequence file after a record is applied; 0 = write-through.</summary>
    public int SequenceFlushMs { get; set; } = 500;

    /// <summary>
    /// Safety margin added to the instant from which the feed's deal stream is known to be complete (this process's
    /// resume point, or the end of a deals replay gap) before the adapter reports it as the start of its deal history
    /// (<see cref="IMT5DealHistory"/>). It absorbs clock skew between the MT5 server that stamps deal times and the
    /// bridge that admits them, so a deal stamped just after the boundary but admitted just before it is never taken
    /// for a ghost by the reconciliation sweep. 5 minutes by default.
    /// </summary>
    public int DealHistoryMarginMs { get; set; } = 300_000;

    /// <summary>
    /// Optional pin: accept only the server certificate with this SHA-1 thumbprint (a self-signed feed certificate).
    /// Empty = the operating system's trust store decides, as for any HTTPS client.
    /// </summary>
    public string CertificateThumbprint { get; set; } = "";

    public string ResolveStatePath()
    {
        if (!string.IsNullOrWhiteSpace(StatePath)) return StatePath;
        var local = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
        var root = string.IsNullOrEmpty(local) ? AppContext.BaseDirectory : Path.Combine(local, "CoverageManager");
        return Path.Combine(root, "livebridge-state.json");
    }
}
